---
- name: Update apt cache
  become: true
  apt:
      update_cache: yes
      cache_valid_time: 3600

- name: Ensure standard packages are installed
  become: true
  apt:
      name: "{{ item }}"
      state: present
  with_items: "{{ desktop_packages }}"
